name: outfit_genie_iot
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^7.6.2
  image_picker: ^0.8.4+2
  file_picker: ^5.0.0
  image_picker_for_web: ^2.1.0
  path_provider: ^2.0.11
  http: ^0.13.4
  shared_preferences: ^2.0.13
  permission_handler: ^10.0.0
  flutter_local_notifications: ^9.0.0+5

flutter_web_plugins:
  sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
