name: outfit_genie_iot

description: A new Flutter project.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  geolocator: ^7.6.2
  http: ^0.13.3
  path_provider: ^2.0.3
  image_picker: ^0.8.4+4
